### ISSUE TITLE
Support grafonnet autocompletion

### ISSUE THREAD

**Issue by v-zhuravlev** [grafana/jsonnet-language-server#110]
Hello!
We now have autocomplete feature, unfortunately it doesn't work for generated grafonnet lib:
https://github.com/grafana/grafonnet

Is there a way to add it? 

This library is very important for designing clean Grafana dashboards as-code. And such autocompletion can add dramatic speed boost to this process, getting near to composing dashboards in Grafana UI.

**Comment by julienduchesne** [comment]
hmm that's tricky. Grafonnet is generated on the fly from jsonschema. To do autocomplete, we'd have to do the same in the language server and it can be a quite expensive thing to do. The language server avoids evaluation at all costs in order to provider sub-second suggestions

**Comment by v-zhuravlev** [comment]
Is this something that can be put behind feature opt-in flag?

**Comment by v-zhuravlev** [comment]
We plan to create Grafana cloud integrations using only that lib as base, so this feature can be game changer.

**Comment by Duologic** [comment]
I've recently learned about LSIF, a format that can store data about an LSP workspace. It would be a bit of a stretch but perhaps we can generate such a file for Grafonnet and tell the language server about it somehow.
