### ISSUE TITLE
Good Jetbrains support

### ISSUE THREAD

**Issue by julienduchesne** [grafana/jsonnet-language-server#15]
We have gotten the feedback that the [Jetbrains LSP support plugin](https://plugins.jetbrains.com/plugin/10209-lsp-support) is not very good. Most features do not work correctly. 

Perhaps we should develop an extension for it, like https://github.com/grafana/vscode-jsonnet? However, a VSCode extension is easy because LSP support is good. Developing the whole LSP support would **not** be easy

Or perhaps we should wait for [Jetbrains Fleet](https://www.jetbrains.com/fleet/) which advertises first-class LSP support and tell people to use that

**Comment by zzehring** [comment]
The [Jebtrains Jsonnet Language Server plugin](https://plugins.jetbrains.com/plugin/18752-jsonnet-language-server) has been released! It's close to feature parity as the vscode-jsonnet extension.

The project/code can be found here: [zzehring/intellij-jsonnet](https://github.com/zzehring/intellij-jsonnet)

For any issues with the new plugin, please post an issue under the project.
