### ISSUE TITLE
Will this project be available through NixPkgs?

### ISSUE THREAD

**Issue by claudio4** [grafana/jsonnet-language-server#42]
I couldn't help but notice that this project has Nix files but it is not submitted to  NixPkgs? Why is this the case? It will be really nice to be able to install this project trough Nix without extra steps.

**Comment by sebastiant** [comment]
It is: https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/development/tools/language-servers/jsonnet-language-server/default.nix

This can be closed
