### ISSUE TITLE
bug: multiple Jsonnet Language Server instances

### ISSUE THREAD

**Issue by davidovich** [grafana/jsonnet-language-server#43]
The language server seems to be started many times:

![image](https://user-images.githubusercontent.com/1440370/169545487-3268f15a-faef-4e5a-8f36-4b340c2cf429.png)

OR if not started many times, the entry in the extensions is not removed.

This may be the cause of non working extension over time.

**Comment by julienduchesne** [comment]
Hey, I moved this issue here: https://github.com/grafana/vscode-jsonnet/issues/10. I'm not having this issue, I can take a look however
