### ISSUE TITLE
Enhancement request: ability to disable "No errors or warnings" diagnostic

### ISSUE THREAD

**Issue by CameronNemo** [grafana/jsonnet-language-server#44]
Most language servers I have used simply do not report anything when there are no errors. Would be nice to be able to switch this diagnostic off. I attached a couple screenshots from NeoVim to show you how it looks in other editors (seems like the repo authors are using VSCode? the diagnostic just might not be as noticeable/bothersome there).

No diagnostic, in edit mode:

![20220523_11h23m41s_grim](https://user-images.githubusercontent.com/3212452/169883065-bfcb35db-ed6e-41ff-b625-b20bab584c9e.png)

Meaningless diagnostic in non-edit mode:

![20220523_11h23m51s_grim](https://user-images.githubusercontent.com/3212452/169883135-fd78bbe3-2490-446c-a308-ab964b778c3f.png)

**Comment by julienduchesne** [comment]
Oh, I meant to take a look at this but completely forgot. Should be pretty easy to resolve, I’ll check it out this week
