### ISSUE TITLE
doesn't work on windows 11

### ISSUE THREAD

**Issue by Midqiu** [grafana/jsonnet-language-server#48]
OS: windows11
time="2022-08-19T17:28:13+08:00" level=info msg="Starting the language server"
time="2022-08-19T17:28:13+08:00" level=info msg="Using tanka mode. Will fall back to the following jpaths: []"
time="2022-08-19T17:28:13+08:00" level=info msg="Initializing jsonnet-language-server version 0.7.2"
time="2022-08-19T17:28:13+08:00" level=info msg="Reading stdlib"
panic: runtime error: index out of range [9] with length 0

goroutine 24 [running]:
github.com/grafana/jsonnet-language-server/pkg/server.(*server).getEvalDiags(0x2020202020202020?, 0xc00012a000)
	/home/runner/work/jsonnet-language-server/jsonnet-language-server/pkg/server/diagnostics.go:153 +0x629
github.com/grafana/jsonnet-language-server/pkg/server.(*server).diagnosticsLoop.func1.1.1()
	/home/runner/work/jsonnet-language-server/jsonnet-language-server/pkg/server/diagnostics.go:55 +0x2a
created by github.com/grafana/jsonnet-language-server/pkg/server.(*server).diagnosticsLoop.func1.1
	/home/runner/work/jsonnet-language-server/jsonnet-language-server/pkg/server/diagnostics.go:54 +0x238
[Info  - 17:28:14] Connection to server got closed. Server will restart.

**Comment by julienduchesne** [comment]
This should be fixed in v0.8.0. Let me know if it still occurs
